"""initial schema

Revision ID: b0b7ad40d309
Revises: 
Create Date: 2026-06-11 21:03:48.490028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b7ad40d309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rl_users_email'), 'rl_users', ['email'], unique=True)
    op.create_index(op.f('ix_rl_users_id'), 'rl_users', ['id'], unique=False)
    op.create_table('rl_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rl_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_rl_api_keys_id'), 'rl_api_keys', ['id'], unique=False)
    op.create_table('rl_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['rl_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rl_request_logs_id'), 'rl_request_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rl_request_logs_id'), table_name='rl_request_logs')
    op.drop_table('rl_request_logs')
    op.drop_index(op.f('ix_rl_api_keys_id'), table_name='rl_api_keys')
    op.drop_table('rl_api_keys')
    op.drop_index(op.f('ix_rl_users_id'), table_name='rl_users')
    op.drop_index(op.f('ix_rl_users_email'), table_name='rl_users')
    op.drop_table('rl_users')
    # ### end Alembic commands ###
